blank_issues_enabled: true
contact_links:
  - name: Have a question about using OpenAPI?
    url: https://communityinviter.com/apps/open-api/openapi
    about: Ask us on our Slack!
  - name: Have a question about OpenAPI Tooling?
    url: https://tools.openapis.org/
    about: Please ask your tooling vendor!
  - name: Want to add to our list of OpenAPI Tools?
    url: https://github.com/OAI/Tooling/issues/new/choose
    about: Open an issue on our tooling site!
  - name: Want to suggest more documentation and examples?
    url: https://github.com/OAI/learn.openapis.org/issues/new
    about: Open an issue on our learning site!
